<font size="+5">#01. Data Tables, Plots & Basic Concepts of Programming</font>

<ul>
    <li>Doubts? â†’ Ask me in <img src="https://emoji.gg/assets/emoji/3970-discord.png" style="height: 1em; vertical-align: middle;"> <a href="https://discord.gg/cmB3KGsqMy">Discord</a></li>
    <li>Tutorials â†’ <img src="https://openmoji.org/php/download_asset.php?type=emoji&emoji_hexcode=E044&emoji_variant=color" style="height: 1em; vertical-align: middle;"> <a href="https://www.youtube.com/channel/UCovCte2I3loteQE_kRsfQcw">YouTube</a></li>
    <li>Book Private Lessons â†’ <span style="color: orange">@</span> <a href="https://sotastica.com/reservar">sotastica</a></li>
</ul>

# Discipline to Search Solutions in Google

> Apply the following steps when **looking for solutions in Google**:
>
> 1. **Necesity**: How to load an Excel in Python?
> 2. **Search in Google**: by keywords
>   - `load excel python`
>   - ~~how to load excel in python~~
> 3. **Solution**: What's the `function()` that loads an Excel in Python?
>   - A Function to Programming is what the Atom to Phisics.
>   - Every time you want to do something in programming
>   - **You will need a `function()`** to make it
>   - Theferore, you must **detect parenthesis `()`**
>   - Out of all the words that you see in a website
>   - Because they indicate the presence of a `function()`.

# Load the Data

> Download [this Excel](https://github.com/sotastica/data/raw/main/internet_usage_spain.xlsx).
> Apply the above discipline and make it happen ðŸš€
> I want to see the table, c'mon ðŸ‘‡

# Preparation

In [23]:
import pandas as pd

In [24]:
df_mortality = pd.read_excel(io='MortalityDataWHR2021C2.xlsx')

In [25]:
df_happiness = pd.read_excel(io='DataForFigure2.1WHR2021C2.xls')

In [26]:
df_regions = df_happiness[['Country name', 'Regional indicator']]

In [27]:
df = df_regions.merge(df_mortality)

In [29]:
df.to_excel('df_mortality_regions.xlsx', index=False)

In [30]:
df = pd.read_excel('df_mortality_regions.xlsx')

In [31]:
df

,Country name,Regional indicator,Population 2020,Population 2019,"COVID-19 deaths per 100,000 population in 2020",Median age,Island,Index of exposure to COVID-19 infections in other countries as of March 31,Log of average distance to SARS countries,WHO Western Pacific Region,Female head of government,Index of institutional trust,Gini coefficient of income,"All-cause death count, 2017","All-cause death count, 2018","All-cause death count, 2019","All-cause death count, 2020","Excess deaths in 2020 per 100,000 population, relative to 2017-2019 average"
0,Finland,Western Europe,5540718.0,5520314.0,10.125000,42.799999,0,2.225083,8.926763,0,1,0.549860,25.9000,53546.0,54394.0,53821.0,55663.0,31.510042
1,Denmark,Western Europe,5792203.0,5818553.0,22.409399,42.299999,0,3.953056,9.006084,0,1,0.571761,27.8000,53103.0,55076.0,53805.0,55477.0,25.533773
2,Switzerland,Western Europe,8654618.0,8574832.0,88.334305,43.099998,0,5.583522,9.078127,0,0,0.660001,30.1000,66703.0,66888.0,67515.0,77087.0,116.680031
3,Iceland,Western Europe,341250.0,361313.0,8.498200,37.299999,1,1.649335,9.069892,0,1,0.325369,24.1000,2229.0,2247.0,2261.0,2321.0,21.445267
4,Netherlands,Western Europe,17134873.0,17332850.0,67.260498,43.200001,0,5.573827,9.059903,0,0,0.522208,27.0000,149805.0,152991.0,151547.0,171175.0,114.468414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,Lesotho,Sub-Saharan Africa,2142252.0,2125268.0,2.380700,24.000000,0,0.586335,9.316565,0,0,0.278961,54.1800,NaN,NaN,NaN,NaN,NaN
144,Botswana,Sub-Saharan Africa,2351625.0,2303697.0,1.786000,25.799999,0,0.627864,9.306540,0,0,0.435331,53.3300,NaN,NaN,NaN,NaN,NaN
145,Rwanda,Sub-Saharan Africa,12952209.0,12626950.0,0.710300,20.299999,0,0.800541,9.173510,0,0,0.905728,43.7100,NaN,NaN,NaN,NaN,NaN
146,Zimbabwe,Sub-Saharan Africa,14862927.0,14645468.0,2.442300,19.600000,0,0.645424,9.244180,0,0,0.286512,40.3625,NaN,NaN,NaN,NaN,NaN
147,Afghanistan,South Asia,38928341.0,38041754.0,5.628300,18.600000,0,1.106935,8.623237,0,0,0.046448,31.0000,NaN,NaN,NaN,NaN,NaN

# Islands

## Number of Islands

In [7]:
df.Island.sum()

20

## Which region had more Islands?

In [8]:
df.groupby('Regional indicator').Island.sum()

Regional indicator
Central and Eastern Europe            0
Commonwealth of Independent States    0
East Asia                             1
Latin America and Caribbean           3
Middle East and North Africa          1
North America and ANZ                 2
South Asia                            2
Southeast Asia                        3
Sub-Saharan Africa                    3
Western Europe                        5
Name: Island, dtype: int64

## Show all Columns for these Islands

In [9]:
mask_region = df['Regional indicator'] == 'Western Europe'

In [10]:
mask_island = df['Island'] == 1

In [11]:
df_europe_islands = df[mask_region & mask_island]

In [12]:
df_europe_islands

,Country name,Regional indicator,Population 2020,Population 2019,"COVID-19 deaths per 100,000 population in 2020",Median age,Island,Index of exposure to COVID-19 infections in other countries as of March 31,Log of average distance to SARS countries,WHO Western Pacific Region,Female head of government,Index of institutional trust,Gini coefficient of income,"All-cause death count, 2017","All-cause death count, 2018","All-cause death count, 2019","All-cause death count, 2020","Excess deaths in 2020 per 100,000 population, relative to 2017-2019 average"
3,Iceland,Western Europe,341250.0,361313.0,8.498200,37.299999,1,1.649335,9.069892,0,1,0.325369,24.10,2229.0,2247.0,2261.0,2321.0,21.445267
14,Ireland,Western Europe,4937796.0,4941444.0,45.303600,38.700001,1,3.188102,9.100494,0,0,0.430625,30.60,NaN,30621.0,30728.0,32271.0,32.320301
16,United Kingdom,Western Europe,67886004.0,66834405.0,108.449501,40.799999,1,5.009473,9.087469,0,0,0.267582,34.07,606874.0,613309.0,600532.0,696705.0,133.313141
22,Malta,Western Europe,441539.0,502653.0,49.599201,42.400002,1,2.822389,9.096670,0,0,0.402808,28.70,3556.0,3672.0,3684.0,4093.0,96.519936
38,Cyprus,Western Europe,875899.0,1198575.0,13.586000,37.299999,1,1.907791,8.967679,0,0,0.174157,29.10,6009.0,5798.0,6218.0,6636.0,60.513317

## Mean Age of across All Islands?

In [13]:
df_europe_islands['Median age'].mean()

39.3

# Female Heads of State

## Number of Countries with Female Heads of State

In [14]:
df['Female head of government'].sum()

22

## Which region had more Female Heads of State?

In [15]:
df.groupby('Regional indicator')['Female head of government'].sum().sort_values(ascending=False)

Regional indicator
Western Europe                        6
Central and Eastern Europe            5
Sub-Saharan Africa                    4
Southeast Asia                        2
South Asia                            2
North America and ANZ                 1
East Asia                             1
Commonwealth of Independent States    1
Middle East and North Africa          0
Latin America and Caribbean           0
Name: Female head of government, dtype: int64

## Show all Columns for these Countries

In [16]:
mask_region = df['Regional indicator'] == 'Western Europe'

In [17]:
mask_female = df['Female head of government'] == 1

In [18]:
df_europe_femaleheads = df[mask_region & mask_female]

In [19]:
df_europe_femaleheads

,Country name,Regional indicator,Population 2020,Population 2019,"COVID-19 deaths per 100,000 population in 2020",Median age,Island,Index of exposure to COVID-19 infections in other countries as of March 31,Log of average distance to SARS countries,WHO Western Pacific Region,Female head of government,Index of institutional trust,Gini coefficient of income,"All-cause death count, 2017","All-cause death count, 2018","All-cause death count, 2019","All-cause death count, 2020","Excess deaths in 2020 per 100,000 population, relative to 2017-2019 average"
0,Finland,Western Europe,5540718.0,5520314.0,10.125000,42.799999,0,2.225083,8.926763,0,1,0.549860,25.9,53546.0,54394.0,53821.0,55663.0,31.510042
1,Denmark,Western Europe,5792203.0,5818553.0,22.409399,42.299999,0,3.953056,9.006084,0,1,0.571761,27.8,53103.0,55076.0,53805.0,55477.0,25.533773
3,Iceland,Western Europe,341250.0,361313.0,8.498200,37.299999,1,1.649335,9.069892,0,1,0.325369,24.1,2229.0,2247.0,2261.0,2321.0,21.445267
5,Norway,Western Europe,5421242.0,5347896.0,8.042400,39.700001,0,2.675678,8.993008,0,1,0.605656,24.8,40634.0,40716.0,40500.0,41155.0,9.997681
12,Germany,Western Europe,83783945.0,83132799.0,40.331100,46.599998,0,4.837829,9.017697,0,1,0.435435,31.1,929351.0,952295.0,936772.0,1000855.0,73.548416
67,Greece,Western Europe,10423056.0,10716322.0,46.416298,45.299999,0,2.327332,9.025694,0,1,0.124216,32.3,124069.0,119952.0,124538.0,132966.0,95.679260

## Mean Age of across All Countries?

In [20]:
df_europe_femaleheads['Median age'].mean()

42.33333269755045

# Pivot Tables

In [21]:
df_panel = pd.read_excel(io='DataPanelWHR2021C2.xls')

In [22]:
df = df_panel.merge(df_regions)

In [23]:
df.pivot_table(index='Regional indicator', columns='year', values='Log GDP per capita')

year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Regional indicator,,,,,,,,,,,,,,,,
Central and Eastern Europe,10.001304,10.153201,9.797326,9.897449,9.790906,9.833528,9.894000,9.902545,9.922598,9.947734,9.984213,10.017978,10.059663,10.101291,10.107383,10.129044
Commonwealth of Independent States,NaN,8.976370,9.150604,9.130109,9.091826,9.145326,9.190536,9.224483,9.269162,9.298407,9.302134,9.317432,9.352217,9.387931,9.424035,9.334375
East Asia,10.529193,10.091370,9.644029,10.027700,10.165273,10.087976,10.139893,10.176389,10.081542,10.257944,10.151036,10.303732,10.335755,10.070882,10.279772,10.081234
Latin America and Caribbean,9.513107,9.104347,9.285042,9.239810,9.315153,9.262799,9.299543,9.331409,9.345498,9.354505,9.351011,9.362934,9.372196,9.407469,9.506585,9.567075
Middle East and North Africa,9.624597,10.153072,9.425606,9.573471,9.765757,9.686885,9.690006,9.702478,9.726380,9.753925,9.682712,9.669662,9.672962,9.778824,9.968624,9.893204
North America and ANZ,10.655180,10.724745,10.730389,10.726743,10.792501,10.716017,10.729894,10.744700,10.757305,10.773755,10.784795,10.793259,10.806098,10.823689,10.831199,10.772623
South Asia,8.217931,8.114056,8.185490,8.075617,8.132140,8.186178,8.215230,8.269632,8.304159,8.341358,8.373923,8.202120,8.444609,8.672683,8.508385,8.587483
Southeast Asia,NaN,9.026495,9.079757,9.108525,9.212401,9.274697,9.215197,8.866032,9.248427,9.289142,9.330076,9.259053,9.254208,9.403344,9.435906,8.941298
Sub-Saharan Africa,NaN,7.673510,7.764225,7.740962,7.789789,7.948720,7.935918,7.994404,8.011251,8.029039,7.960720,8.062397,8.070166,8.076758,8.125856,8.422257
Western Europe,10.685362,10.778038,10.742737,10.778830,10.738708,10.723870,10.726707,10.747961,10.711840,10.757469,10.789569,10.809325,10.831039,10.845563,10.860944,10.766422

## Which Region had a higher

# Achieved Goals

_Double click on **this cell** and place an `X` inside the square brackets (i.e., [X]) if you think you understand the goal:_

- [ ] Identify the **Elements of Programming** thanks to the syntax.
- [ ] Use `functions` that belongs to external `libraries`.
- [ ] Get _the machine to work for you, not against you_.
  - [ ] `shift + tab` to ask help to Python.
  - [ ] `tab` to ask Python for suggestions.
- [ ] Understand that a `dog` doesn't make `miau()`. But, rather `guau()`... the same way a `DataFrame` cannot `fly()` (i.e., `DataFrame.fly()`?).
- [ ] All roads lead to Rome; We can achieve the **the same result with different lines of code**.
  - We reproduced a scatterplot using 3 different lines of code.